django_inline_formset/django_inline_formset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')), # 2nd
]

django_inline_formset/products/urls.py
from django.urls import path

from .views import (
    ProductList, ProductCreate, ProductUpdate,
    delete_image, delete_variant
)

app_name = 'products'  # 3rd

urlpatterns = [
    path('products/', ProductList.as_view(), name='list_products'),
    path('create/', ProductCreate.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdate.as_view(), name='update_product'),
    path('delete-image/<int:pk>/', delete_image, name='delete_image'),
    path('delete-variant/<int:pk>/', delete_variant, name='delete_variant'),
]

django_inline_formset/products/models.py
# 4th

from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=150)
    short_description = models.TextField(max_length=100)

    def __str__(self):
        return self.title


class Image(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, null=True
        )
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.product.title


class Variant(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
        )
    size = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.product.title

django_inline_formset/products/forms.py
# 6th

from django import forms
from django.forms import inlineformset_factory

from .models import (
    Product, Image, Variant
)


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'short_description': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
        }


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = '__all__'


class VariantForm(forms.ModelForm):

    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'size': forms.TextInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'quantity': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
            'price': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                    }
                ),
        }


VariantFormSet = inlineformset_factory(
    Product, Variant, form=VariantForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)
ImageFormSet = inlineformset_factory(
    Product, Image, form=ImageForm,
    extra=1, can_delete=True,
    can_delete_extra=True
)

django_inline_formset/products/views.py
# 6th
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.edit import (
    CreateView, UpdateView
)

from .forms import (
    ProductForm, VariantFormSet, ImageFormSet
)
from .models import (
    Image,
    Product,
    Variant
)


class ProductInline():
    form_class = ProductForm
    model = Product
    template_name = "products/product_create_or_update.html"

    def form_valid(self, form):
        named_formsets = self.get_named_formsets()
        if not all((x.is_valid() for x in named_formsets.values())):
            return self.render_to_response(self.get_context_data(form=form))

        self.object = form.save()

        # for every formset, attempt to find a specific formset save function
        # otherwise, just save.
        for name, formset in named_formsets.items():
            formset_save_func = getattr(self, 'formset_{0}_valid'.format(name), None)
            if formset_save_func is not None:
                formset_save_func(formset)
            else:
                formset.save()
        return redirect('products:list_products')

    def formset_variants_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        variants = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this, if you have can_delete=True parameter set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for variant in variants:
            variant.product = self.object
            variant.save()

    def formset_images_valid(self, formset):
        """
        Hook for custom formset saving.. useful if you have multiple formsets
        """
        images = formset.save(commit=False)  # self.save_formset(formset, contact)
        # add this, if you have can_delete=True parameter set in inlineformset_factory func
        for obj in formset.deleted_objects:
            obj.delete()
        for image in images:
            image.product = self.object
            image.save()


class ProductCreate(ProductInline, CreateView):

    def get_context_data(self, **kwargs):
        ctx = super(ProductCreate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        if self.request.method == "GET":
            return {
                'variants': VariantFormSet(prefix='variants'),
                'images': ImageFormSet(prefix='images'),
            }
        else:
            return {
                'variants': VariantFormSet(self.request.POST or None, self.request.FILES or None, prefix='variants'),
                'images': ImageFormSet(self.request.POST or None, self.request.FILES or None, prefix='images'),
            }

    
class ProductUpdate(ProductInline, UpdateView):

    def get_context_data(self, **kwargs):
        ctx = super(ProductUpdate, self).get_context_data(**kwargs)
        ctx['named_formsets'] = self.get_named_formsets()
        return ctx

    def get_named_formsets(self):
        return {
            'variants': VariantFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='variants'),
            'images': ImageFormSet(self.request.POST or None, self.request.FILES or None, instance=self.object, prefix='images'),
        }


def delete_image(request, pk):
    try:
        image = Image.objects.get(id=pk)
    except Image.DoesNotExist:
        messages.success(
            request, 'Object Does not exit'
            )
        return redirect('products:update_product', pk=image.product.id)

    image.delete()
    messages.success(
            request, 'Image deleted successfully'
            )
    return redirect('products:update_product', pk=image.product.id)


def delete_variant(request, pk):
    try:
        variant = Variant.objects.get(id=pk)
    except Variant.DoesNotExist:
        messages.success(
            request, 'Object Does not exit'
            )
        return redirect('products:update_product', pk=variant.product.id)

    variant.delete()
    messages.success(
            request, 'Variant deleted successfully'
            )
    return redirect('products:update_product', pk=variant.product.id)


class ProductList(ListView):
    model = Product
    template_name = "products/product_list.html"
    context_object_name = "products"

django_inline_formset/templates/base.html
<!DOCTYPE html>
<html>

<head>
  {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
  <div class="wrapper">
        <!-- Page Content  -->
        {% block content %}{% endblock %}
    </div>
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

django_inline_formset/templates/products/product_create_or_update.html
<!-- product_create_or_update.html -->

{% extends "base.html" %}

{% block content %}
<form enctype="multipart/form-data" class="container" method="post" id="product_form">
    {% csrf_token %}
    <!-- main form start --- in our case product form -->
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Add Products</h4>
        </div>
        {% for field in form %}
            <div class="form-group card-body">
                <label>{{field.label}}</label>
                {% if field.field.required %}
                    <span style="color: red;" class="required">*</span>
                {% endif %}
            
                {{field}}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <!-- main form end --- in our case product form -->

    <!-- inline form for Images start -->

    <!-- EXPLAINING with named_formsets.images as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here images is our ImageFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.images as formset %}  
        {{ formset.management_form }}
        <script type="text/html" id="images-template">   // id="inlineformsetname-template"
            <tr id="images-__prefix__" class= hide_all>  // id="inlineformsetname-__prefix__"
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>

        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Add Images</h4>
            </div>
            <table class="table card-body">
                <thead class="text-secondary">
                    <th>Image <span style="color: red;" class="required">*</span></th>
                    <th>Delete?</th>
                    <th>Custom Delete btn</th>
                </thead>
                <tbody id="item-images">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="images-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                </td>
                            {% endfor %}
                            <!-- delete code -->
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                        Delete
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'products:delete_image' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>            
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-image-button" class="btn btn-secondary add-images">Add More</a> <!-- id="add-inlineformsetname-button" -->
        </div>
    {% endwith %}
    <!-- inline form for Images end -->

    <!-- inline form for Variant start -->

    <!-- EXPLAINING with named_formsets.variants as formset -->
    <!-- Note: named_formsets is used in get_context_data function in views.py -->
    <!-- Note: here variants is our VariantFormSet name, used in get_named_formsets function in views.py -->
    {% with named_formsets.variants as formset %}
        {{ formset.management_form }}
        <script type="text/html" id="variants-template">  // id="inlineformsetname-template"
            // id='inlineformsetname-__prefix__' 
            <tr id="variants-__prefix__" class= hide_all>
                {% for fields in formset.empty_form.hidden_fields %}
                    {{ fields }}
                {% endfor %}
            
                {% for fields in formset.empty_form.visible_fields %}
                    <td>{{fields}}</td>
                {% endfor %}
            </tr>
        </script>
        <div class="table-responsive card mt-4">
            <div class="card-header card-header-secondary">
                <h4 class="card-title">Add Variants</h4>
            </div>
            <table class="table card-header">
                <thead class="text-secondary">
                    <th>Size <span style="color: red;" class="required">*</span></th>
                    <th>Quantity <span style="color: red;" class="required">*</span></th>
                    <th>Price <span style="color: red;" class="required">*</span></th>
                    <th>Delete?</th>
                    <th>Custom Delete btn</th>
                </thead>
                <tbody id="item-variants">  <!-- id="item-inlineformsetname" -->
                    <!-- formset non forms errors -->
                    {% for error in formset.non_form_errors %}
                        <span style="color: red">{{ error }}</span>
                    {% endfor %}
                    {% for formss in formset %}
                        {{ formss.management_form }}
                        <tr id="variants-{{ forloop.counter0 }}" class= hide_all>  <!-- id="inlineformsetname-counter" -->
                            {{ formss.id }}
                            {% for field in formss.visible_fields %}
                                <td>
                                    {{field}}
                                    {% for error in field.errors %}
                                        <span style="color: red">{{ error }}</span>
                                    {% endfor %}
                                    
                                    {% comment %} {{ field.DELETE }} {% endcomment %}
                                </td>
                            {% endfor %}
                            {% comment %} for delete {% endcomment %}
                            {% if formss.instance.pk %}
                                <td>
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal{{formss.instance.pk}}">
                                        Delete
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade" id="exampleModal{{formss.instance.pk}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel{{formss.instance.pk}}" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel{{formss.instance.pk}}">Are Your Sure You Want To Delete This?</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'products:delete_variant' formss.instance.pk %}" type="button" class="btn btn-primary">Yes, Delete</a>
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </td>            
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a href="#" id="add-variant-button" class="btn btn-secondary add-variants">Add More</a> <!-- id="add-inlineformsetname-button" -->
        </div>
        
        {% endwith %}
        <!-- inline form for Images end -->

        <div class="form-group">
            <button type="submit" class="btn btn-secondary btn-block">Submit</button>
        </div>
</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
    $(document).ready(function() {
        // when user clicks add more btn of images
      $('.add-images').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-images').children().length;
          var tmplMarkup = $('#images-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-images').append(compiledTmpl);
  
          // update form count
          $('#id_images-TOTAL_FORMS').attr('value', count+1);
      });
  });

  $(document).ready(function() {
    // when user clicks add more btn of variants
      $('.add-variants').click(function(ev) {
          ev.preventDefault();
          var count = $('#item-variants').children().length;
          var tmplMarkup = $('#variants-template').html();
          var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
          $('#item-variants').append(compiledTmpl);
  
          // update form count
          $('#id_variants-TOTAL_FORMS').attr('value', count+1);
      });
  });
</script>
        
{% endblock content %}

django_inline_formset/templates/products/product_list.html
<!-- product_list.html -->
{% extends "base.html" %}


{% block content %}
    <div class="card">
        <div class="card-header card-header-secondary">
            <h4 class="card-title">Products</h4>
            <a href="{% url 'products:create_product' %}">Add more products</a>
        </div>
        <ul>
            {% for product in products %}
                <li class="card-body">{{ product.title }} | <a href="{% url 'products:update_product' product.id %}">Edit</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}